apiVersion: v1
kind: Service
metadata:
  name: vault-cluster-addr
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: vault
  ports:
    - name: cluster-addr
      port: 8201
      targetPort: 8201