output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

# output "kubectl_config" {
#    description = "kubectl config as generated by the module."
#    value       = module.eks.kubeconfig
# }

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.aws_auth_configmap_yaml
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "db_instance_address" {
  description = "The address of the RDS instance"
  value       = module.db_default.db_instance_address
}

output "db_instance_arn" {
  description = "The ARN of the RDS instance"
  value       = module.db_default.db_instance_arn
}

output "db_instance_availability_zone" {
  description = "The availability zone of the RDS instance"
  value       = module.db_default.db_instance_availability_zone
}

output "database_subnet_group_name" {
  description = "module.vpc.database_subnet_group_name"
  value = module.vpc.database_subnet_group_name
}

output "database_subnet_group" {
  description = "module.vpc.database_subnet_group"
  value = module.vpc.database_subnet_group
}

output "db_instance_username" {
  description = "DB username"
  value       = module.db_default.db_instance_username
  sensitive = true
}

output "db_instance_password" {
  description = "DB password"
  value       = module.db_default.db_instance_password
  sensitive = true
}


