---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: curlpod
  name: curlpod
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: curlpod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curlpod
  name: curlpod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curlpod
  template:
    metadata:
      labels:
        app: curlpod
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: curl-container
        image: curlimages/curl:latest
        command: ["tail", "-f", "/dev/null"]
      restartPolicy: Always

