global:
  name: consul
  datacenter: dc1
  tls:
    enabled: false
  metrics:
    enabled: true
    enableAgentMetrics: true
server:
  replicas: 3
  connect: true
client:
  enabled: true
  grpc: true
dns:
  enabled: true
  type: ClusterIP
syncCatalog:
  enabled: true
  default: true
  toConsul: true
  toK8S: true
ui:
  enabled: true
  service:
    type: NodePort
connectInject:
  enabled: true
  replicas: 1
  default: true
  transparentProxy:
    defaultEnabled: true
metrics:
  defaultEnabled: true
  defaultEnableMerging: true
controller:
  enabled: true
apiGateway:
  enabled: true
  image: "hashicorp/consul-api-gateway:0.1.0"
  managedGatewayClass:
    serviceType: LoadBalancer
prometheus:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1
ingressGateways:
  enabled: true
  defaults:
    replicas: 1
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer
        ports:
          - port: 9090
          - port: 8080
terminatingGateways:
  enabled: true
  defaults:
    replicas: 1
webhookCertManager:
  tolerations: null