# Available parameters and their default values for the Vault chart.

global:
  enabled: true
  tlsDisable: true

injector:
  enabled: true
  replicas: 1

server:
  enabled: true
  # dev:
  #   enabled: true
    # devRootToken: "root"
  enterpriseLicense:
    secretName: "vault"
    secretKey: "license"
  image:
    repository: "hashicorp/vault-enterprise"
    tag: "1.13.1-ent"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    labels:
      app: vault
  # extraSecretEnvironmentVars: 
  #   - envName: AWS_SECRET_ACCESS_KEY
  #     secretName: vault
  #     secretKey: AWS_SECRET_ACCESS_KEY
  #   - envName: AWS_ACCESS_KEY_ID
  #     secretName: vault
  #     secretKey: AWS_ACCESS_KEY_ID
  #   - envName: AWS_SESSION_TOKEN
  #     secretName: vault
  #     secretKey: AWS_SESSION_TOKEN
  #   - envName: AWS_REGION
  #     secretName: vault
  #     secretKey: AWS_REGION
  ha:
    enabled: true
    replicas: 1
    raft: 
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          # Enable unauthenticated metrics access (necessary for Prometheus Operator)
          #telemetry {
          #  unauthenticated_metrics_access = "true"
          #}
        }
        
        storage "raft" {
          path = "/vault/data"
        }
        service_registration "kubernetes" {}
        ui            = true
        cluster_addr  = "http://0.0.0.0:8201"
        api_addr      = "http://0.0.0.0:8200"
  # standalone:
  #   enabled: "-"
  #   config: |
  #     ui = true

  #     listener "tcp" {
  #       tls_disable = 1
  #       address = "[::]:8200"
  #       cluster_address = "[::]:8201"
  #       # Enable unauthenticated metrics access (necessary for Prometheus Operator)
  #       #telemetry {
  #       #  unauthenticated_metrics_access = "true"
  #       #}
  #     }
  #     storage "file" {
  #       path = "/vault/data"
  #     }
  service:
    enabled: true
    type: ClusterIP
    port: 8200
    targetPort: 8200

ui:
  enabled: true
  serviceType: "LoadBalancer"
  externalPort: 8200

csi:
  enabled: false
  image:
    repository: "hashicorp/vault-csi-provider"
    tag: "0.2.0"
    pullPolicy: IfNotPresent

