# Available parameters and their default values for the Vault chart.

global:
  enabled: true
  tlsDisable: true

server:
  image:
    repository: "hashicorp/vault"
    tag: "1.15.2"
  enabled: true
  type: ClusterIP
  dev:
    enabled: true
    devRootToken: "root"
  annotations:
    consul.hashicorp.com/kubernetes-service: 'vault' 
    consul.hashicorp.com/connect-inject: "true"
  extraLabels: 
    consul.hashicorp.com/connect-inject: "true"
  service:
    enabled: true
    annotations:
       consul.hashicorp.com/kubernetes-service: 'vault' 
       consul.hashicorp.com/connect-inject: "true"
    extraLabels: 
       consul.hashicorp.com/connect-inject: "true"
     
injector:
  enabled: false

ui:
  enabled: true
  serviceType: "ClusterIP"
  externalPort: 8200
  annotations:
       consul.hashicorp.com/service-ignore: "true"
  extraLabels: 
       consul.hashicorp.com/service-ignore: "true"
     




